#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Demo.Droid.Resource", IsApplication=true)]

namespace Demo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_addButtonColorNormal = global::Demo.Droid.Resource.Attribute.fab_addButtonColorNormal;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_addButtonColorPressed = global::Demo.Droid.Resource.Attribute.fab_addButtonColorPressed;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_addButtonPlusIconColor = global::Demo.Droid.Resource.Attribute.fab_addButtonPlusIconColor;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_addButtonSize = global::Demo.Droid.Resource.Attribute.fab_addButtonSize;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_addButtonStrokeVisible = global::Demo.Droid.Resource.Attribute.fab_addButtonStrokeVisible;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_colorDisabled = global::Demo.Droid.Resource.Attribute.fab_colorDisabled;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_colorNormal = global::Demo.Droid.Resource.Attribute.fab_colorNormal;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_colorPressed = global::Demo.Droid.Resource.Attribute.fab_colorPressed;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_expandDirection = global::Demo.Droid.Resource.Attribute.fab_expandDirection;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_icon = global::Demo.Droid.Resource.Attribute.fab_icon;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_labelStyle = global::Demo.Droid.Resource.Attribute.fab_labelStyle;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_labelsPosition = global::Demo.Droid.Resource.Attribute.fab_labelsPosition;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_plusIconColor = global::Demo.Droid.Resource.Attribute.fab_plusIconColor;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_size = global::Demo.Droid.Resource.Attribute.fab_size;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_stroke_visible = global::Demo.Droid.Resource.Attribute.fab_stroke_visible;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Attribute.fab_title = global::Demo.Droid.Resource.Attribute.fab_title;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Color.fab_normal = global::Demo.Droid.Resource.Color.fab_normal;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Color.fab_pressed = global::Demo.Droid.Resource.Color.fab_pressed;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_actions_spacing = global::Demo.Droid.Resource.Dimension.fab_actions_spacing;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_icon_size = global::Demo.Droid.Resource.Dimension.fab_icon_size;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_labels_margin = global::Demo.Droid.Resource.Dimension.fab_labels_margin;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_plus_icon_size = global::Demo.Droid.Resource.Dimension.fab_plus_icon_size;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_plus_icon_stroke = global::Demo.Droid.Resource.Dimension.fab_plus_icon_stroke;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_shadow_offset = global::Demo.Droid.Resource.Dimension.fab_shadow_offset;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_shadow_radius = global::Demo.Droid.Resource.Dimension.fab_shadow_radius;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_size_mini = global::Demo.Droid.Resource.Dimension.fab_size_mini;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_size_normal = global::Demo.Droid.Resource.Dimension.fab_size_normal;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Dimension.fab_stroke_width = global::Demo.Droid.Resource.Dimension.fab_stroke_width;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Drawable.fab_bg_mini = global::Demo.Droid.Resource.Drawable.fab_bg_mini;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Drawable.fab_bg_normal = global::Demo.Droid.Resource.Drawable.fab_bg_normal;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Id.down = global::Demo.Droid.Resource.Id.down;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Id.fab_expand_menu_button = global::Demo.Droid.Resource.Id.fab_expand_menu_button;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Id.fab_label = global::Demo.Droid.Resource.Id.fab_label;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Id.left = global::Demo.Droid.Resource.Id.left;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Id.mini = global::Demo.Droid.Resource.Id.mini;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Id.normal = global::Demo.Droid.Resource.Id.normal;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Id.right = global::Demo.Droid.Resource.Id.right;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Id.up = global::Demo.Droid.Resource.Id.up;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.String.ApplicationName = global::Demo.Droid.Resource.String.ApplicationName;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.String.Hello = global::Demo.Droid.Resource.String.Hello;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.AddFloatingActionButton = global::Demo.Droid.Resource.Styleable.AddFloatingActionButton;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.AddFloatingActionButton_fab_plusIconColor = global::Demo.Droid.Resource.Styleable.AddFloatingActionButton_fab_plusIconColor;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionButton = global::Demo.Droid.Resource.Styleable.FloatingActionButton;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::Demo.Droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::Demo.Droid.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::Demo.Droid.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionButton_fab_icon = global::Demo.Droid.Resource.Styleable.FloatingActionButton_fab_icon;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionButton_fab_size = global::Demo.Droid.Resource.Styleable.FloatingActionButton_fab_size;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionButton_fab_stroke_visible = global::Demo.Droid.Resource.Styleable.FloatingActionButton_fab_stroke_visible;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionButton_fab_title = global::Demo.Droid.Resource.Styleable.FloatingActionButton_fab_title;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionsMenu = global::Demo.Droid.Resource.Styleable.FloatingActionsMenu;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonColorNormal = global::Demo.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonColorNormal;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonColorPressed = global::Demo.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonColorPressed;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonPlusIconColor = global::Demo.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonPlusIconColor;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonSize = global::Demo.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonSize;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonStrokeVisible = global::Demo.Droid.Resource.Styleable.FloatingActionsMenu_fab_addButtonStrokeVisible;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionsMenu_fab_expandDirection = global::Demo.Droid.Resource.Styleable.FloatingActionsMenu_fab_expandDirection;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionsMenu_fab_labelStyle = global::Demo.Droid.Resource.Styleable.FloatingActionsMenu_fab_labelStyle;
			global::NativeCode.Mobile.Controls.FloatingActions.Droid.Resource.Styleable.FloatingActionsMenu_fab_labelsPosition = global::Demo.Droid.Resource.Styleable.FloatingActionsMenu_fab_labelsPosition;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Animation.dialog_main_hide_amination = global::Demo.Droid.Resource.Animation.dialog_main_hide_amination;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Animation.dialog_main_show_amination = global::Demo.Droid.Resource.Animation.dialog_main_show_amination;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Animation.dialog_root_hide_amin = global::Demo.Droid.Resource.Animation.dialog_root_hide_amin;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Animation.dialog_root_show_amin = global::Demo.Droid.Resource.Animation.dialog_root_show_amin;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Animation.progress_indeterminate_animation = global::Demo.Droid.Resource.Animation.progress_indeterminate_animation;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Animation.snackbar_hide_animation = global::Demo.Droid.Resource.Animation.snackbar_hide_animation;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Animation.snackbar_show_animation = global::Demo.Droid.Resource.Animation.snackbar_show_animation;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.animate = global::Demo.Droid.Resource.Attribute.animate;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.check = global::Demo.Droid.Resource.Attribute.check;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.checkBoxSize = global::Demo.Droid.Resource.Attribute.checkBoxSize;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.clickAfterRipple = global::Demo.Droid.Resource.Attribute.clickAfterRipple;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.iconDrawable = global::Demo.Droid.Resource.Attribute.iconDrawable;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.iconSize = global::Demo.Droid.Resource.Attribute.iconSize;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.max = global::Demo.Droid.Resource.Attribute.max;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.min = global::Demo.Droid.Resource.Attribute.min;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.progress = global::Demo.Droid.Resource.Attribute.progress;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.ringWidth = global::Demo.Droid.Resource.Attribute.ringWidth;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.rippleBorderRadius = global::Demo.Droid.Resource.Attribute.rippleBorderRadius;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.rippleColor = global::Demo.Droid.Resource.Attribute.rippleColor;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.rippleSpeed = global::Demo.Droid.Resource.Attribute.rippleSpeed;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.showNumberIndicator = global::Demo.Droid.Resource.Attribute.showNumberIndicator;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.thumbSize = global::Demo.Droid.Resource.Attribute.thumbSize;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Attribute.value = global::Demo.Droid.Resource.Attribute.value;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Color.green = global::Demo.Droid.Resource.Color.green;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Color.thumbColor = global::Demo.Droid.Resource.Color.thumbColor;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.background_button = global::Demo.Droid.Resource.Drawable.background_button;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.background_button_float = global::Demo.Droid.Resource.Drawable.background_button_float;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.background_button_rectangle = global::Demo.Droid.Resource.Drawable.background_button_rectangle;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.background_checkbox = global::Demo.Droid.Resource.Drawable.background_checkbox;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.background_checkbox_check = global::Demo.Droid.Resource.Drawable.background_checkbox_check;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.background_checkbox_uncheck = global::Demo.Droid.Resource.Drawable.background_checkbox_uncheck;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.background_progress = global::Demo.Droid.Resource.Drawable.background_progress;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.background_switch_ball_uncheck = global::Demo.Droid.Resource.Drawable.background_switch_ball_uncheck;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.background_transparent = global::Demo.Droid.Resource.Drawable.background_transparent;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.dialog_background = global::Demo.Droid.Resource.Drawable.dialog_background;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.float_button1_shadowp = global::Demo.Droid.Resource.Drawable.float_button1_shadowp;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.float_button_shadow1 = global::Demo.Droid.Resource.Drawable.float_button_shadow1;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.ic_launcher = global::Demo.Droid.Resource.Drawable.ic_launcher;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.ic_reloj_max = global::Demo.Droid.Resource.Drawable.ic_reloj_max;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.shadow_down = global::Demo.Droid.Resource.Drawable.shadow_down;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.shadow_right = global::Demo.Droid.Resource.Drawable.shadow_right;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Drawable.sprite_check = global::Demo.Droid.Resource.Drawable.sprite_check;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.blue = global::Demo.Droid.Resource.Id.blue;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.button_accept = global::Demo.Droid.Resource.Id.button_accept;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.button_cancel = global::Demo.Droid.Resource.Id.button_cancel;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.buttonflat = global::Demo.Droid.Resource.Id.buttonflat;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.contentDialog = global::Demo.Droid.Resource.Id.contentDialog;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.contentSelector = global::Demo.Droid.Resource.Id.contentSelector;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.dialog_rootView = global::Demo.Droid.Resource.Id.dialog_rootView;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.green = global::Demo.Droid.Resource.Id.green;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.message = global::Demo.Droid.Resource.Id.message;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.message_scrollView = global::Demo.Droid.Resource.Id.message_scrollView;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.number_indicator_spinner_content = global::Demo.Droid.Resource.Id.number_indicator_spinner_content;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.progressBarCircularIndetermininate = global::Demo.Droid.Resource.Id.progressBarCircularIndetermininate;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.red = global::Demo.Droid.Resource.Id.red;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.rootSelector = global::Demo.Droid.Resource.Id.rootSelector;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.shape_bacground = global::Demo.Droid.Resource.Id.shape_bacground;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.snackbar = global::Demo.Droid.Resource.Id.snackbar;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.text = global::Demo.Droid.Resource.Id.text;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.title = global::Demo.Droid.Resource.Id.title;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Id.viewColor = global::Demo.Droid.Resource.Id.viewColor;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Layout.checkbox_view = global::Demo.Droid.Resource.Layout.checkbox_view;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Layout.color_selector = global::Demo.Droid.Resource.Layout.color_selector;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Layout.dialog = global::Demo.Droid.Resource.Layout.dialog;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Layout.flatbutton_view = global::Demo.Droid.Resource.Layout.flatbutton_view;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Layout.number_indicator_spinner = global::Demo.Droid.Resource.Layout.number_indicator_spinner;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Layout.progress_dialog = global::Demo.Droid.Resource.Layout.progress_dialog;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Layout.rectanglebutton_view = global::Demo.Droid.Resource.Layout.rectanglebutton_view;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Layout.snackbar = global::Demo.Droid.Resource.Layout.snackbar;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Layout.switch_view = global::Demo.Droid.Resource.Layout.switch_view;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.String.ApplicationName = global::Demo.Droid.Resource.String.ApplicationName;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.String.Hello = global::Demo.Droid.Resource.String.Hello;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes = global::Demo.Droid.Resource.Styleable.CustomAttributes;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_animate = global::Demo.Droid.Resource.Styleable.CustomAttributes_animate;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_check = global::Demo.Droid.Resource.Styleable.CustomAttributes_check;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_checkBoxSize = global::Demo.Droid.Resource.Styleable.CustomAttributes_checkBoxSize;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_clickAfterRipple = global::Demo.Droid.Resource.Styleable.CustomAttributes_clickAfterRipple;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_iconDrawable = global::Demo.Droid.Resource.Styleable.CustomAttributes_iconDrawable;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_iconSize = global::Demo.Droid.Resource.Styleable.CustomAttributes_iconSize;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_max = global::Demo.Droid.Resource.Styleable.CustomAttributes_max;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_min = global::Demo.Droid.Resource.Styleable.CustomAttributes_min;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_progress = global::Demo.Droid.Resource.Styleable.CustomAttributes_progress;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_ringWidth = global::Demo.Droid.Resource.Styleable.CustomAttributes_ringWidth;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_rippleBorderRadius = global::Demo.Droid.Resource.Styleable.CustomAttributes_rippleBorderRadius;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_rippleColor = global::Demo.Droid.Resource.Styleable.CustomAttributes_rippleColor;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_rippleSpeed = global::Demo.Droid.Resource.Styleable.CustomAttributes_rippleSpeed;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_showNumberIndicator = global::Demo.Droid.Resource.Styleable.CustomAttributes_showNumberIndicator;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_thumbSize = global::Demo.Droid.Resource.Styleable.CustomAttributes_thumbSize;
			global::NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource.Styleable.CustomAttributes_value = global::Demo.Droid.Resource.Styleable.CustomAttributes_value;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Demo.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Demo.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int dialog_main_hide_amination = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dialog_main_show_amination = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dialog_root_hide_amin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dialog_root_show_amin = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int progress_indeterminate_animation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int snackbar_hide_animation = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int snackbar_show_animation = 2130968582;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000d
			public const int animate = 2130771981;
			
			// aapt resource value: 0x7f010008
			public const int check = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int checkBoxSize = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public const int clickAfterRipple = 2130771983;
			
			// aapt resource value: 0x7f010019
			public const int fab_addButtonColorNormal = 2130771993;
			
			// aapt resource value: 0x7f010018
			public const int fab_addButtonColorPressed = 2130771992;
			
			// aapt resource value: 0x7f01001b
			public const int fab_addButtonPlusIconColor = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int fab_addButtonSize = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int fab_addButtonStrokeVisible = 2130771996;
			
			// aapt resource value: 0x7f010012
			public const int fab_colorDisabled = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int fab_colorNormal = 2130771987;
			
			// aapt resource value: 0x7f010011
			public const int fab_colorPressed = 2130771985;
			
			// aapt resource value: 0x7f01001f
			public const int fab_expandDirection = 2130771999;
			
			// aapt resource value: 0x7f010014
			public const int fab_icon = 2130771988;
			
			// aapt resource value: 0x7f01001d
			public const int fab_labelStyle = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int fab_labelsPosition = 2130771998;
			
			// aapt resource value: 0x7f010010
			public const int fab_plusIconColor = 2130771984;
			
			// aapt resource value: 0x7f010015
			public const int fab_size = 2130771989;
			
			// aapt resource value: 0x7f010017
			public const int fab_stroke_visible = 2130771991;
			
			// aapt resource value: 0x7f010016
			public const int fab_title = 2130771990;
			
			// aapt resource value: 0x7f01000b
			public const int iconDrawable = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int iconSize = 2130771980;
			
			// aapt resource value: 0x7f010003
			public const int max = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int min = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int progress = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int ringWidth = 2130771975;
			
			// aapt resource value: 0x7f01000e
			public const int rippleBorderRadius = 2130771982;
			
			// aapt resource value: 0x7f010000
			public const int rippleColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int rippleSpeed = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int showNumberIndicator = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int thumbSize = 2130771978;
			
			// aapt resource value: 0x7f010005
			public const int value = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int fab_normal = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int fab_pressed = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int green = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int thumbColor = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int fab_actions_spacing = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int fab_icon_size = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int fab_labels_margin = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int fab_plus_icon_size = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int fab_plus_icon_stroke = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int fab_shadow_offset = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int fab_shadow_radius = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int fab_size_mini = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int fab_size_normal = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int fab_stroke_width = 2131099657;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_button_float = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_button_rectangle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background_checkbox = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background_checkbox_check = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int background_checkbox_uncheck = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int background_progress = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int background_switch_ball_uncheck = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int background_transparent = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dialog_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fab_bg_mini = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int fab_bg_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int float_button1_shadowp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int float_button_shadow1 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_launcher = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_reloj_max = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int shadow_down = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int shadow_right = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sprite_check = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int blue = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int button_accept = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int button_cancel = 2131165203;
			
			// aapt resource value: 0x7f070018
			public const int buttonflat = 2131165208;
			
			// aapt resource value: 0x7f07000f
			public const int contentDialog = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int contentSelector = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int dialog_rootView = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int down = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int fab_expand_menu_button = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int fab_label = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int green = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int left = 2131165188;
			
			// aapt resource value: 0x7f070012
			public const int message = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int message_scrollView = 2131165201;
			
			// aapt resource value: 0x7f070002
			public const int mini = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int normal = 2131165187;
			
			// aapt resource value: 0x7f070015
			public const int number_indicator_spinner_content = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int progressBarCircularIndetermininate = 2131165206;
			
			// aapt resource value: 0x7f07000b
			public const int red = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int right = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int rootSelector = 2131165192;
			
			// aapt resource value: 0x7f07001a
			public const int shape_bacground = 2131165210;
			
			// aapt resource value: 0x7f070017
			public const int snackbar = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int text = 2131165209;
			
			// aapt resource value: 0x7f070010
			public const int title = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int up = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int viewColor = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int checkbox_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int color_selector = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int flatbutton_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int number_indicator_spinner = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int progress_dialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int rectanglebutton_view = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int snackbar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int switch_view = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AddFloatingActionButton = new int[] {
					2130771984};
			
			// aapt resource value: 0
			public const int AddFloatingActionButton_fab_plusIconColor = 0;
			
			public static int[] CustomAttributes = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 13
			public const int CustomAttributes_animate = 13;
			
			// aapt resource value: 8
			public const int CustomAttributes_check = 8;
			
			// aapt resource value: 9
			public const int CustomAttributes_checkBoxSize = 9;
			
			// aapt resource value: 15
			public const int CustomAttributes_clickAfterRipple = 15;
			
			// aapt resource value: 11
			public const int CustomAttributes_iconDrawable = 11;
			
			// aapt resource value: 12
			public const int CustomAttributes_iconSize = 12;
			
			// aapt resource value: 3
			public const int CustomAttributes_max = 3;
			
			// aapt resource value: 4
			public const int CustomAttributes_min = 4;
			
			// aapt resource value: 6
			public const int CustomAttributes_progress = 6;
			
			// aapt resource value: 7
			public const int CustomAttributes_ringWidth = 7;
			
			// aapt resource value: 14
			public const int CustomAttributes_rippleBorderRadius = 14;
			
			// aapt resource value: 0
			public const int CustomAttributes_rippleColor = 0;
			
			// aapt resource value: 1
			public const int CustomAttributes_rippleSpeed = 1;
			
			// aapt resource value: 2
			public const int CustomAttributes_showNumberIndicator = 2;
			
			// aapt resource value: 10
			public const int CustomAttributes_thumbSize = 10;
			
			// aapt resource value: 5
			public const int CustomAttributes_value = 5;
			
			public static int[] FloatingActionButton = new int[] {
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorDisabled = 1;
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorNormal = 2;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_icon = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_size = 4;
			
			// aapt resource value: 6
			public const int FloatingActionButton_fab_stroke_visible = 6;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_title = 5;
			
			public static int[] FloatingActionsMenu = new int[] {
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999};
			
			// aapt resource value: 1
			public const int FloatingActionsMenu_fab_addButtonColorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionsMenu_fab_addButtonColorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionsMenu_fab_addButtonPlusIconColor = 3;
			
			// aapt resource value: 2
			public const int FloatingActionsMenu_fab_addButtonSize = 2;
			
			// aapt resource value: 4
			public const int FloatingActionsMenu_fab_addButtonStrokeVisible = 4;
			
			// aapt resource value: 7
			public const int FloatingActionsMenu_fab_expandDirection = 7;
			
			// aapt resource value: 5
			public const int FloatingActionsMenu_fab_labelStyle = 5;
			
			// aapt resource value: 6
			public const int FloatingActionsMenu_fab_labelsPosition = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
