#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NativeCode.Mobile.Controls.FloatingActions.Droid.Resource", IsApplication=false)]

namespace NativeCode.Mobile.Controls.FloatingActions.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public static int fab_addButtonColorNormal = 2130771977;
			
			// aapt resource value: 0x7f010008
			public static int fab_addButtonColorPressed = 2130771976;
			
			// aapt resource value: 0x7f01000b
			public static int fab_addButtonPlusIconColor = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public static int fab_addButtonSize = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public static int fab_addButtonStrokeVisible = 2130771980;
			
			// aapt resource value: 0x7f010002
			public static int fab_colorDisabled = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int fab_colorNormal = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int fab_colorPressed = 2130771969;
			
			// aapt resource value: 0x7f01000f
			public static int fab_expandDirection = 2130771983;
			
			// aapt resource value: 0x7f010004
			public static int fab_icon = 2130771972;
			
			// aapt resource value: 0x7f01000d
			public static int fab_labelStyle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public static int fab_labelsPosition = 2130771982;
			
			// aapt resource value: 0x7f010000
			public static int fab_plusIconColor = 2130771968;
			
			// aapt resource value: 0x7f010005
			public static int fab_size = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int fab_stroke_visible = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int fab_title = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public static int fab_normal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int fab_pressed = 2130903041;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int fab_actions_spacing = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int fab_icon_size = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int fab_labels_margin = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int fab_plus_icon_size = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int fab_plus_icon_stroke = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int fab_shadow_offset = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int fab_shadow_radius = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int fab_size_mini = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int fab_size_normal = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int fab_stroke_width = 2131034121;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int fab_bg_mini = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int fab_bg_normal = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public static int down = 2131099654;
			
			// aapt resource value: 0x7f060000
			public static int fab_expand_menu_button = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int fab_label = 2131099649;
			
			// aapt resource value: 0x7f060004
			public static int left = 2131099652;
			
			// aapt resource value: 0x7f060002
			public static int mini = 2131099650;
			
			// aapt resource value: 0x7f060003
			public static int normal = 2131099651;
			
			// aapt resource value: 0x7f060005
			public static int right = 2131099653;
			
			// aapt resource value: 0x7f060007
			public static int up = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AddFloatingActionButton = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public static int AddFloatingActionButton_fab_plusIconColor = 0;
			
			public static int[] FloatingActionButton = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 1
			public static int FloatingActionButton_fab_colorDisabled = 1;
			
			// aapt resource value: 2
			public static int FloatingActionButton_fab_colorNormal = 2;
			
			// aapt resource value: 0
			public static int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public static int FloatingActionButton_fab_icon = 3;
			
			// aapt resource value: 4
			public static int FloatingActionButton_fab_size = 4;
			
			// aapt resource value: 6
			public static int FloatingActionButton_fab_stroke_visible = 6;
			
			// aapt resource value: 5
			public static int FloatingActionButton_fab_title = 5;
			
			public static int[] FloatingActionsMenu = new int[] {
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public static int FloatingActionsMenu_fab_addButtonColorNormal = 1;
			
			// aapt resource value: 0
			public static int FloatingActionsMenu_fab_addButtonColorPressed = 0;
			
			// aapt resource value: 3
			public static int FloatingActionsMenu_fab_addButtonPlusIconColor = 3;
			
			// aapt resource value: 2
			public static int FloatingActionsMenu_fab_addButtonSize = 2;
			
			// aapt resource value: 4
			public static int FloatingActionsMenu_fab_addButtonStrokeVisible = 4;
			
			// aapt resource value: 7
			public static int FloatingActionsMenu_fab_expandDirection = 7;
			
			// aapt resource value: 5
			public static int FloatingActionsMenu_fab_labelStyle = 5;
			
			// aapt resource value: 6
			public static int FloatingActionsMenu_fab_labelsPosition = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
