#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NativeCode.Mobile.Controls.MaterialDesign.Droid.Resource", IsApplication=false)]

namespace NativeCode.Mobile.Controls.MaterialDesign.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int dialog_main_hide_amination = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int dialog_main_show_amination = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int dialog_root_hide_amin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int dialog_root_show_amin = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int progress_indeterminate_animation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int snackbar_hide_animation = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int snackbar_show_animation = 2130968582;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000d
			public static int animate = 2130771981;
			
			// aapt resource value: 0x7f010008
			public static int check = 2130771976;
			
			// aapt resource value: 0x7f010009
			public static int checkBoxSize = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public static int clickAfterRipple = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public static int iconDrawable = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int iconSize = 2130771980;
			
			// aapt resource value: 0x7f010003
			public static int max = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int min = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int progress = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int ringWidth = 2130771975;
			
			// aapt resource value: 0x7f01000e
			public static int rippleBorderRadius = 2130771982;
			
			// aapt resource value: 0x7f010000
			public static int rippleColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int rippleSpeed = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int showNumberIndicator = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public static int thumbSize = 2130771978;
			
			// aapt resource value: 0x7f010005
			public static int value = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public static int green = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int thumbColor = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int background_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int background_button_float = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int background_button_rectangle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int background_checkbox = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int background_checkbox_check = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int background_checkbox_uncheck = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int background_progress = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int background_switch_ball_uncheck = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int background_transparent = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int dialog_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int float_button1_shadowp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int float_button_shadow1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int ic_launcher = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int ic_reloj_max = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int shadow_down = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int shadow_right = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int sprite_check = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public static int blue = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public static int button_accept = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public static int button_cancel = 2131165195;
			
			// aapt resource value: 0x7f070010
			public static int buttonflat = 2131165200;
			
			// aapt resource value: 0x7f070007
			public static int contentDialog = 2131165191;
			
			// aapt resource value: 0x7f070001
			public static int contentSelector = 2131165185;
			
			// aapt resource value: 0x7f070006
			public static int dialog_rootView = 2131165190;
			
			// aapt resource value: 0x7f070004
			public static int green = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public static int message = 2131165194;
			
			// aapt resource value: 0x7f070009
			public static int message_scrollView = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public static int number_indicator_spinner_content = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public static int progressBarCircularIndetermininate = 2131165198;
			
			// aapt resource value: 0x7f070003
			public static int red = 2131165187;
			
			// aapt resource value: 0x7f070000
			public static int rootSelector = 2131165184;
			
			// aapt resource value: 0x7f070012
			public static int shape_bacground = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public static int snackbar = 2131165199;
			
			// aapt resource value: 0x7f070011
			public static int text = 2131165201;
			
			// aapt resource value: 0x7f070008
			public static int title = 2131165192;
			
			// aapt resource value: 0x7f070002
			public static int viewColor = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int checkbox_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int color_selector = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int flatbutton_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int number_indicator_spinner = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int progress_dialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int rectanglebutton_view = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int snackbar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int switch_view = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomAttributes = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 13
			public static int CustomAttributes_animate = 13;
			
			// aapt resource value: 8
			public static int CustomAttributes_check = 8;
			
			// aapt resource value: 9
			public static int CustomAttributes_checkBoxSize = 9;
			
			// aapt resource value: 15
			public static int CustomAttributes_clickAfterRipple = 15;
			
			// aapt resource value: 11
			public static int CustomAttributes_iconDrawable = 11;
			
			// aapt resource value: 12
			public static int CustomAttributes_iconSize = 12;
			
			// aapt resource value: 3
			public static int CustomAttributes_max = 3;
			
			// aapt resource value: 4
			public static int CustomAttributes_min = 4;
			
			// aapt resource value: 6
			public static int CustomAttributes_progress = 6;
			
			// aapt resource value: 7
			public static int CustomAttributes_ringWidth = 7;
			
			// aapt resource value: 14
			public static int CustomAttributes_rippleBorderRadius = 14;
			
			// aapt resource value: 0
			public static int CustomAttributes_rippleColor = 0;
			
			// aapt resource value: 1
			public static int CustomAttributes_rippleSpeed = 1;
			
			// aapt resource value: 2
			public static int CustomAttributes_showNumberIndicator = 2;
			
			// aapt resource value: 10
			public static int CustomAttributes_thumbSize = 10;
			
			// aapt resource value: 5
			public static int CustomAttributes_value = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
